# Generated by Django 5.0.6 on 2024-06-22 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_linkprecedence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='linkPrecedence',
            field=models.CharField(choices=[('secondary', 'Secondary'), ('primary', 'Primary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
    ]
